---
- hosts: all
  become: true

  vars:
    webserver_stack: webserver


  tasks:

    - name: Create a directory if it does not exist
      file:
        path: /etc/nginx
        state: directory
        mode: '0755'

    - name: Update nginx files
      copy:
        src: ./files/nginx/
        dest: /etc/nginx/
      register: nginx_files

    - name: Ensure nginx is redeployable
      docker_stack:
        state: absent
        name: "{{ webserver_stack }}"
        compose:
          - /etc/nginx/stack.yml
      run_once: true
      when: "nginx_files.changed"

    - name: Install nginx
      docker_stack:
        state: present
        name: "{{ webserver_stack }}"
        compose:
          - /etc/nginx/stack.yml
      run_once: true
