version: "3.7"

services:
  traefik:
    image: traefik:v2.0.5
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme-data:/var/acme
    networks:
      - proxy-public
    configs:
      - source: traefik_yml
        target: /etc/traefik/traefik.yml
        mode: 444
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.25'
          memory: 48m

configs:
  traefik_yml:
    file: ./traefik.yml

volumes:
  acme-data:

networks:
  proxy-public:
    external: true
