
entryPoints:
  http:
    address: ":80"
  http-secure:
    address: ":443"

providers:
  docker:
    swarmMode: true
    network: proxy-public
    exposedByDefault: false

api:
  insecure: true
  dashboard: true

certificatesResolvers:
  sample:
    acme:
      email: "sorend@gmail.com"
      storage: "/var/acme/acme.json"
      httpChallenge:
        entrypoint: "http"
